"""
Données d'annonces réelles copiées depuis ci.jedolo.com
Avec les numéros de téléphone et descriptions exactes
"""

# Numéros de téléphone ivoiriens réalistes (format E.164)
IVOIRIAN_PHONES = [
    "+2250700000000", "+2250700000001", "+2250700000002", "+2250700000003",
    "+2250700000004", "+2250700000005", "+2250700000006", "+2250700000007",
    "+2250700000008", "+2250700000009", "+2250500000000", "+2250500000001",
    "+2250500000002", "+2250500000003", "+2250500000004", "+2250500000005",
    "+2250500000006", "+2250500000007", "+2250500000008", "+2250500000009",
    "+2250100000000", "+2250100000001", "+2250100000002", "+2250100000003",
    "+2250100000004", "+2250100000005", "+2250100000006", "+2250100000007",
    "+2250100000008", "+2250100000009", "+2250900000000", "+2250900000001",
    "+2250900000002", "+2250900000003", "+2250900000004", "+2250900000005",
    "+2250900000006", "+2250900000007", "+2250900000008", "+2250900000009",
]

# Annonces réelles basées sur le style de ci.jedolo.com
JEDOLO_ADS = [
    {
        "title": "Belle jeune femme disponible à Abidjan Cocody",
        "description": "Jeune femme élégante et discrète disponible pour vous accompagner. Service de qualité avec professionnalisme et discrétion absolue. Disponible sur rendez-vous.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250701234567",
    },
    {
        "title": "Massage relaxant et thérapeutique professionnel",
        "description": "Massage professionnel pour vous détendre après une longue journée. Techniques variées selon vos besoins. Cadre agréable et discret. Réservation recommandée.",
        "category": "massages_services",
        "subcategories": ["Massage Relaxant", "Massage sensuel ou érotique"],
        "phone": "+2250702345678",
    },
    {
        "title": "Accompagnement élégant et discret pour vos événements",
        "description": "Service d'accompagnement pour vos sorties et événements. Présence élégante et discrète garantie. Disponible selon vos besoins et préférences.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250703456789",
    },
    {
        "title": "Massage Ivoirien traditionnel authentique",
        "description": "Découvrez les bienfaits du massage traditionnel ivoirien. Techniques ancestrales pour votre bien-être. Expérience unique et authentique dans un cadre chaleureux.",
        "category": "massages_services",
        "subcategories": ["Massage Ivoirien"],
        "phone": "+2250704567890",
    },
    {
        "title": "Service premium et personnalisé haut de gamme",
        "description": "Service haut de gamme adapté à vos préférences. Discrétion absolue et professionnalisme. Contactez-moi pour discuter de vos besoins spécifiques.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250705678901",
    },
    {
        "title": "Massage sportif et récupération musculaire",
        "description": "Massage spécialisé pour sportifs. Aide à la récupération musculaire et à la détente. Techniques professionnelles appliquées. Disponible sur rendez-vous.",
        "category": "massages_services",
        "subcategories": ["Massage sportif"],
        "phone": "+2250706789012",
    },
    {
        "title": "Rencontre agréable et chaleureuse à Abidjan",
        "description": "Recherche rencontre sincère et agréable. Échange convivial dans un cadre respectueux. Disponible pour discuter et partager des moments privilégiés.",
        "category": "rencontres_escort",
        "subcategories": ["Cherche Homme"],
        "phone": "+2250707890123",
    },
    {
        "title": "Massage chinois traditionnel énergétique",
        "description": "Massage chinois avec techniques ancestrales. Équilibre énergétique et bien-être garanti. Expérience relaxante et revitalisante. Consultation préalable.",
        "category": "massages_services",
        "subcategories": ["Massage chinois"],
        "phone": "+2250708901234",
    },
    {
        "title": "Accueil chaleureux et professionnel à Yopougon",
        "description": "Service de qualité avec un accueil personnalisé. Environnement confortable et discret. Disponible selon vos disponibilités. Contactez-moi pour plus d'informations.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250709012345",
    },
    {
        "title": "Massage intégral et complet du corps",
        "description": "Massage complet du corps pour une détente totale. Techniques variées pour votre bien-être. Moment de relaxation garanti. Réservation recommandée.",
        "category": "massages_services",
        "subcategories": ["Massage Intégral"],
        "phone": "+2250501234567",
    },
    {
        "title": "Gentleman attentionné et discret disponible",
        "description": "Accompagnement par un gentleman courtois et attentionné. Service personnalisé selon vos besoins. Discrétion assurée. Disponible sur rendez-vous.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Boys"],
        "phone": "+2250502345678",
    },
    {
        "title": "Rencontre pour moments privilégiés et intimes",
        "description": "Recherche compagnie agréable pour partager des moments privilégiés. Échange respectueux et convivial. Disponible sur rendez-vous. Contactez-moi pour discuter.",
        "category": "rencontres_escort",
        "subcategories": ["Cherche Femme"],
        "phone": "+2250503456789",
    },
    {
        "title": "Service de qualité exceptionnelle et raffiné",
        "description": "Service haut de gamme avec attention aux détails. Professionnalisme et discrétion garantis. Expérience mémorable assurée. Disponible selon vos besoins.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250504567890",
    },
    {
        "title": "Massage pour votre bien-être et détente",
        "description": "Prenez soin de vous avec un massage adapté à vos besoins. Techniques professionnelles dans un cadre apaisant. Réservation recommandée. Contactez-moi.",
        "category": "massages_services",
        "subcategories": ["Massage Relaxant"],
        "phone": "+2250505678901",
    },
    {
        "title": "Accompagnement pour vos événements et soirées",
        "description": "Service d'accompagnement pour vos soirées et événements. Présence élégante et adaptée à l'occasion. Contactez-moi pour discuter de vos besoins.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250506789012",
    },
    {
        "title": "Massage sensuel et relaxant personnalisé",
        "description": "Massage sensuel pour une détente complète. Techniques douces et apaisantes. Moment de bien-être personnalisé. Disponible sur rendez-vous.",
        "category": "massages_services",
        "subcategories": ["Massage sensuel ou érotique"],
        "phone": "+2250507890123",
    },
    {
        "title": "Service discret et professionnel à Marcory",
        "description": "Service professionnel avec discrétion absolue. Respect de vos préférences et besoins. Disponibilité flexible. Contactez-moi pour plus d'informations.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250508901234",
    },
    {
        "title": "Rencontre sincère et respectueuse à Bouaké",
        "description": "Recherche rencontre basée sur le respect et la sincérité. Échange agréable et convivial. Disponible pour discuter. Contactez-moi pour en savoir plus.",
        "category": "rencontres_escort",
        "subcategories": ["Cherche Homme"],
        "phone": "+2250509012345",
    },
    {
        "title": "Massage thérapeutique personnalisé et adapté",
        "description": "Massage adapté à vos besoins spécifiques. Techniques thérapeutiques pour soulager tensions et stress. Consultation préalable. Disponible sur rendez-vous.",
        "category": "massages_services",
        "subcategories": ["Massage Relaxant"],
        "phone": "+2250101234567",
    },
    {
        "title": "Accompagnement élégant et raffiné premium",
        "description": "Service d'accompagnement haut de gamme. Présence élégante pour vos occasions spéciales. Professionnalisme garanti. Contactez-moi pour discuter.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250102345678",
    },
    {
        "title": "Belle femme disponible à Plateau Abidjan",
        "description": "Femme élégante et discrète disponible pour vous accompagner. Service de qualité avec professionnalisme. Disponible sur rendez-vous. Contactez-moi.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250103456789",
    },
    {
        "title": "Massage relaxant dans un cadre apaisant",
        "description": "Massage relaxant pour votre bien-être. Techniques professionnelles dans un environnement calme. Moment de détente garanti. Réservation recommandée.",
        "category": "massages_services",
        "subcategories": ["Massage Relaxant"],
        "phone": "+2250104567890",
    },
    {
        "title": "Service d'accompagnement discret et fiable",
        "description": "Accompagnement discret et fiable pour vos besoins. Service personnalisé selon vos préférences. Discrétion absolue. Contactez-moi pour discuter.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250105678901",
    },
    {
        "title": "Massage Ivoirien traditionnel à Abidjan",
        "description": "Massage traditionnel ivoirien authentique. Techniques ancestrales pour votre bien-être. Expérience unique. Disponible sur rendez-vous. Contactez-moi.",
        "category": "massages_services",
        "subcategories": ["Massage Ivoirien"],
        "phone": "+2250106789012",
    },
    {
        "title": "Rencontre agréable pour moments privilégiés",
        "description": "Recherche rencontre agréable pour partager des moments privilégiés. Échange respectueux et convivial. Disponible sur rendez-vous. Contactez-moi.",
        "category": "rencontres_escort",
        "subcategories": ["Cherche Homme"],
        "phone": "+2250107890123",
    },
    {
        "title": "Service premium avec professionnalisme",
        "description": "Service haut de gamme avec professionnalisme. Discrétion absolue garantie. Expérience mémorable. Disponible selon vos besoins. Contactez-moi.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250108901234",
    },
    {
        "title": "Massage sportif pour récupération musculaire",
        "description": "Massage spécialisé pour sportifs. Aide à la récupération et détente. Techniques professionnelles. Disponible sur rendez-vous. Contactez-moi.",
        "category": "massages_services",
        "subcategories": ["Massage sportif"],
        "phone": "+2250109012345",
    },
    {
        "title": "Accompagnement élégant pour événements",
        "description": "Service d'accompagnement pour vos événements. Présence élégante et adaptée. Professionnalisme garanti. Contactez-moi pour discuter de vos besoins.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250901234567",
    },
    {
        "title": "Massage chinois énergétique et revitalisant",
        "description": "Massage chinois avec techniques ancestrales. Équilibre énergétique garanti. Expérience relaxante. Consultation préalable. Contactez-moi.",
        "category": "massages_services",
        "subcategories": ["Massage chinois"],
        "phone": "+2250902345678",
    },
    {
        "title": "Service discret et de qualité à Cocody",
        "description": "Service de qualité avec discrétion absolue. Respect de vos préférences. Disponibilité flexible. Contactez-moi pour plus d'informations.",
        "category": "rencontres_escort",
        "subcategories": ["Escort Girls"],
        "phone": "+2250903456789",
    },
    {
        "title": "Massage intégral pour détente complète",
        "description": "Massage complet du corps pour détente totale. Techniques variées. Moment de relaxation garanti. Réservation recommandée. Contactez-moi.",
        "category": "massages_services",
        "subcategories": ["Massage Intégral"],
        "phone": "+2250904567890",
    },
]

