# Generated by Django 5.1.2 on 2025-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.CharField(
                choices=[
                    ("rencontres_escort", "Rencontres et escortes"),
                    ("massages_services", "Massages et services"),
                    ("produits_adultes", "Produits adultes"),
                ],
                max_length=20,
            ),
        ),
    ]
