# Generated by Django 5.1.2 on 2025-10-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["name"],
                "verbose_name": "Ville",
                "verbose_name_plural": "Villes",
            },
        ),
    ]
