# Generated by Django 5.1.2 on 2025-10-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="Profile verified by email"),
        ),
    ]
