# Generated by Django 5.1.2 on 2025-10-28 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_e164",
            field=models.CharField(
                blank=True,
                help_text="Phone number in E.164 format, e.g., +2250700000000",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+[1-9]\\d{1,14}$", message="Enter a valid E.164 phone."
                    )
                ],
            ),
        ),
    ]
